//Title: Programa10 Cap.9   			Filename:P10.Swift
//Author: JAZMIN E. CRESPO C		Date: February 2017
//Description: Problema 27
//Input: -
//Output: Interes a pagar



import Foundation

print("Supóngase que le prestan $2,000 al 9% de intéres por año durante 5 años. ¿Qué intéres debe pagar?.")
print(" ")
print(" ")

var inte :Double = 0.9
var porA :Double

porA = ((2000 * 0.9) + 2000) * 5




print("$",porA,"dlls")
