/*
Nombre del programa: ..................Determinar si un entero dado es un multiplo de 6 *--------------------------------------------------	
 Creado por: Carlos Gastelum Nieves ..........  
 No Control: .................................................14210456 
 Fecha ......................................................17-02-2017
 Practicas Swift del libro..........................................

Patrones de diseño
Capitulo I
Practica 8:
*/




let resta
let numUNO = 42
let numDOS = 7

if  resta == 0 {
	print (numUNO "Si es  multiplo de" numDOS)

	}
	else {
	print (numUNO "No es multiplo de "numDOS) 
}